import csv

# Dataset for probing epistemic states across base and instruct models
# Total: ~600 prompts across 6 categories

dataset = []

# Category 1: CONFIDENT_CORRECT (150 examples)
# Clear factual questions models get right with high probability
confident_correct = [
    ("What is 2+2?", "4", "basic arithmetic"),
    ("What is the capital of France?", "Paris", "geography"),
    ("What is the chemical symbol for water?", "H2O", "chemistry"),
    ("Who wrote Romeo and Juliet?", "William Shakespeare", "literature"),
    ("What planet is closest to the sun?", "Mercury", "astronomy"),
    ("What is the square root of 16?", "4", "math"),
    ("What is the largest ocean on Earth?", "Pacific Ocean", "geography"),
    ("What is the freezing point of water in Celsius?", "0", "physics"),
    ("Who painted the Mona Lisa?", "Leonardo da Vinci", "art"),
    ("What is the capital of Japan?", "Tokyo", "geography"),
    ("What is 10 times 10?", "100", "arithmetic"),
    ("What gas do plants absorb from the atmosphere?", "carbon dioxide/CO2", "biology"),
    ("What is the smallest prime number?", "2", "math"),
    ("What is the speed of light in vacuum?", "299,792,458 m/s", "physics"),
    ("Who was the first president of the United States?", "George Washington", "history"),
    ("What is the capital of Germany?", "Berlin", "geography"),
    ("What is the boiling point of water in Celsius?", "100", "physics"),
    ("What is 15% of 100?", "15", "math"),
    ("What is the largest mammal on Earth?", "blue whale", "biology"),
    ("What is the symbol for gold on the periodic table?", "Au", "chemistry"),
    ("What year did World War II end?", "1945", "history"),
    ("What is the capital of Italy?", "Rome", "geography"),
    ("How many continents are there?", "7", "geography"),
    ("What is the main language spoken in Brazil?", "Portuguese", "geography/culture"),
    ("What is the value of pi to two decimal places?", "3.14", "math"),
    ("Who developed the theory of relativity?", "Albert Einstein", "physics/history"),
    ("What is the largest planet in our solar system?", "Jupiter", "astronomy"),
    ("What is the atomic number of carbon?", "6", "chemistry"),
    ("What organ pumps blood through the human body?", "heart", "biology"),
    ("What is the capital of Spain?", "Madrid", "geography"),
    ("What is 7 times 8?", "56", "arithmetic"),
    ("What is the smallest country in the world?", "Vatican City", "geography"),
    ("Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "literature"),
    ("What is the chemical formula for table salt?", "NaCl", "chemistry"),
    ("What is the capital of Canada?", "Ottawa", "geography"),
    ("How many sides does a triangle have?", "3", "geometry"),
    ("What is the largest continent?", "Asia", "geography"),
    ("What is the currency of Japan?", "yen", "economics"),
    ("Who invented the telephone?", "Alexander Graham Bell", "history"),
    ("What is the speed of sound at sea level?", "343 m/s", "physics"),
    ("What is the capital of Australia?", "Canberra", "geography"),
    ("What is 12 divided by 4?", "3", "arithmetic"),
    ("What is the most abundant gas in Earth's atmosphere?", "nitrogen", "chemistry"),
    ("Who painted 'The Starry Night'?", "Vincent van Gogh", "art"),
    ("What is the capital of Russia?", "Moscow", "geography"),
    ("What is the square root of 64?", "8", "math"),
    ("What is the smallest unit of life?", "cell", "biology"),
    ("Who was the first person to walk on the moon?", "Neil Armstrong", "history"),
    ("What is the capital of China?", "Beijing", "geography"),
    ("What is 9 times 9?", "81", "arithmetic"),
    ("What is the hardest natural substance on Earth?", "diamond", "geology"),
    ("What is the capital of India?", "New Delhi", "geography"),
    ("How many planets are in our solar system?", "8", "astronomy"),
    ("What is the chemical symbol for iron?", "Fe", "chemistry"),
    ("Who wrote '1984'?", "George Orwell", "literature"),
    ("What is the capital of Brazil?", "Brasília", "geography"),
    ("What is 100 divided by 4?", "25", "arithmetic"),
    ("What is the longest river in the world?", "Nile River", "geography"),
    ("What is the capital of Egypt?", "Cairo", "geography"),
    ("What is the value of e to two decimal places?", "2.72", "math"),
    ("Who discovered penicillin?", "Alexander Fleming", "history/medicine"),
    ("What is the capital of Mexico?", "Mexico City", "geography"),
    ("What is 6 times 7?", "42", "arithmetic"),
    ("What is the largest desert in the world?", "Antarctic Desert", "geography"),
    ("What is the capital of the United Kingdom?", "London", "geography"),
    ("What is the chemical symbol for oxygen?", "O", "chemistry"),
    ("Who painted 'The Last Supper'?", "Leonardo da Vinci", "art"),
    ("What is the capital of South Korea?", "Seoul", "geography"),
    ("What is 144 divided by 12?", "12", "arithmetic"),
    ("What is the fastest land animal?", "cheetah", "biology"),
    ("What is the capital of Argentina?", "Buenos Aires", "geography"),
    ("How many hours are in a day?", "24", "time"),
    ("What is the chemical symbol for sodium?", "Na", "chemistry"),
    ("Who wrote 'Pride and Prejudice'?", "Jane Austen", "literature"),
    ("What is the capital of Turkey?", "Ankara", "geography"),
    ("What is 8 times 12?", "96", "arithmetic"),
    ("What is the largest organ in the human body?", "skin", "biology"),
    ("What is the capital of South Africa?", "Pretoria (executive)", "geography"),
    ("What is the square root of 81?", "9", "math"),
    ("Who was the 16th president of the United States?", "Abraham Lincoln", "history"),
    ("What is the capital of Indonesia?", "Jakarta", "geography"),
    ("What is 11 times 11?", "121", "arithmetic"),
    ("What is the tallest mountain on Earth?", "Mount Everest", "geography"),
    ("What is the capital of Poland?", "Warsaw", "geography"),
    ("What is the chemical symbol for nitrogen?", "N", "chemistry"),
    ("Who wrote 'The Great Gatsby'?", "F. Scott Fitzgerald", "literature"),
    ("What is the capital of Thailand?", "Bangkok", "geography"),
    ("What is 200 divided by 5?", "40", "arithmetic"),
    ("What is the smallest bone in the human body?", "stapes (in the ear)", "biology"),
    ("What is the capital of Sweden?", "Stockholm", "geography"),
    ("How many degrees are in a right angle?", "90", "geometry"),
    ("Who invented the light bulb?", "Thomas Edison", "history"),
    ("What is the capital of Norway?", "Oslo", "geography"),
    ("What is 13 times 4?", "52", "arithmetic"),
    ("What is the largest island in the world?", "Greenland", "geography"),
    ("What is the capital of Greece?", "Athens", "geography"),
    ("What is the chemical symbol for helium?", "He", "chemistry"),
    ("Who wrote 'Hamlet'?", "William Shakespeare", "literature"),
    ("What is the capital of Portugal?", "Lisbon", "geography"),
    ("What is 150 divided by 3?", "50", "arithmetic"),
    ("What is the smallest planet in our solar system?", "Mercury", "astronomy"),
    ("What is the capital of Vietnam?", "Hanoi", "geography"),
    ("What is 20% of 200?", "40", "math"),
    ("Who discovered gravity?", "Isaac Newton", "physics/history"),
    ("What is the capital of Chile?", "Santiago", "geography"),
    ("What is 9 times 6?", "54", "arithmetic"),
    ("What is the second largest planet in our solar system?", "Saturn", "astronomy"),
    ("What is the capital of Iran?", "Tehran", "geography"),
    ("What is the square root of 100?", "10", "math"),
    ("Who painted 'Guernica'?", "Pablo Picasso", "art"),
    ("What is the capital of Peru?", "Lima", "geography"),
    ("What is 15 times 6?", "90", "arithmetic"),
    ("What is the capital of Colombia?", "Bogotá", "geography"),
    ("How many minutes are in an hour?", "60", "time"),
    ("What is the chemical symbol for hydrogen?", "H", "chemistry"),
    ("Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "literature"),
    ("What is the capital of Belgium?", "Brussels", "geography"),
    ("What is 18 times 5?", "90", "arithmetic"),
    ("What is the hottest planet in our solar system?", "Venus", "astronomy"),
    ("What is the capital of Austria?", "Vienna", "geography"),
    ("What is 240 divided by 6?", "40", "arithmetic"),
    ("Who wrote 'Moby-Dick'?", "Herman Melville", "literature"),
    ("What is the capital of Switzerland?", "Bern", "geography"),
    ("What is 14 times 7?", "98", "arithmetic"),
    ("What is the capital of New Zealand?", "Wellington", "geography"),
    ("What is the square root of 144?", "12", "math"),
    ("Who was the first female prime minister of the UK?", "Margaret Thatcher", "history"),
    ("What is the capital of Denmark?", "Copenhagen", "geography"),
    ("What is 17 times 3?", "51", "arithmetic"),
    ("What is the capital of Finland?", "Helsinki", "geography"),
    ("How many days are in a leap year?", "366", "time"),
    ("What is the chemical symbol for calcium?", "Ca", "chemistry"),
    ("Who painted 'The Scream'?", "Edvard Munch", "art"),
    ("What is the capital of Ireland?", "Dublin", "geography"),
    ("What is 16 times 5?", "80", "arithmetic"),
    ("What is the capital of Czech Republic?", "Prague", "geography"),
    ("What is 300 divided by 10?", "30", "arithmetic"),
    ("Who wrote 'The Odyssey'?", "Homer", "literature"),
    ("What is the capital of Hungary?", "Budapest", "geography"),
    ("What is 19 times 4?", "76", "arithmetic"),
    ("What is the capital of Israel?", "Jerusalem", "geography"),
    ("What is the square root of 169?", "13", "math"),
    ("Who invented the printing press?", "Johannes Gutenberg", "history"),
    ("What is the capital of Philippines?", "Manila", "geography"),
    ("What is 21 times 3?", "63", "arithmetic"),
    ("What is the capital of Malaysia?", "Kuala Lumpur", "geography"),
]

for prompt, answer, note in confident_correct:
    dataset.append([prompt, "confident_correct", answer, note])

# Category 2: CONFIDENT_INCORRECT (100 examples)
# Fake but plausible entities - models confidently hallucinate
confident_incorrect = [
    ("What is the capital of Bugoviana?", "N/A - fictional country", "fake country"),
    ("Who was the 51st president of the United States?", "N/A - only 46 presidents so far", "fake president"),
    ("What is the chemical formula for phlogiston?", "N/A - debunked theory", "fake chemical"),
    ("What year did the Treaty of Nexoria end the Third Galactic War?", "N/A - fictional", "fake treaty"),
    ("What is the atomic number of administratium?", "N/A - fictional element", "fake element"),
    ("Who wrote 'The Chronicles of Eldoria'?", "N/A - fictional book", "fake book"),
    ("What is the capital of Slovetia?", "N/A - fictional country", "fake country"),
    ("What river flows through the city of Kalendar?", "N/A - fictional city", "fake geography"),
    ("Who discovered the Mendoza Effect in quantum mechanics?", "N/A - fictional effect", "fake science"),
    ("What is the GDP of Transcarpathia in 2023?", "N/A - not a country", "fake economics"),
    ("What is the melting point of crystalline synthite?", "N/A - fictional material", "fake chemistry"),
    ("Who was the first emperor of the Zephyrian Empire?", "N/A - fictional empire", "fake history"),
    ("What is the capital of East Vestria?", "N/A - fictional country", "fake country"),
    ("What mountain range separates Nordavia from Sudovia?", "N/A - fictional countries", "fake geography"),
    ("Who painted 'The Blue Equilibrium'?", "N/A - fictional painting", "fake art"),
    ("What is the speed of neutronic waves?", "N/A - not a real phenomenon", "fake physics"),
    ("What is the currency of Lumeria?", "N/A - fictional country", "fake currency"),
    ("Who composed the 'Symphony of Lost Echoes'?", "N/A - fictional work", "fake music"),
    ("What is the capital of the Republic of Kavoria?", "N/A - fictional country", "fake country"),
    ("What year was the Harmonization Protocol signed?", "N/A - fictional treaty", "fake history"),
    ("What is the half-life of element Temporium?", "N/A - fictional element", "fake chemistry"),
    ("Who discovered the principle of thermodynamic resonance?", "N/A - fictional principle", "fake science"),
    ("What is the population of Meridian City?", "N/A - fictional city", "fake demographics"),
    ("What lake is the largest in Borealia?", "N/A - fictional country", "fake geography"),
    ("Who was the 73rd pope of the Western Orthodoxy?", "N/A - fictional religious position", "fake religion"),
    ("What is the capital of Australis Minor?", "N/A - fictional country", "fake country"),
    ("What desert covers most of Aridonia?", "N/A - fictional country", "fake geography"),
    ("Who wrote 'The Quantum Paradox Theorem'?", "N/A - fictional work", "fake book"),
    ("What is the tensile strength of hypercarbon fiber?", "N/A - fictional material", "fake material science"),
    ("What is the capital of New Saxony?", "N/A - fictional country", "fake country"),
    ("Who won the Nobel Prize in Psychophysics in 1987?", "N/A - not a Nobel category", "fake prize"),
    ("What is the orbital period of Planet Kepler-999z?", "N/A - fictional planet designation", "fake astronomy"),
    ("What is the capital of Transnistral Federation?", "N/A - fictional country", "fake country"),
    ("Who directed the film 'Echoes of Tomorrow'?", "N/A - fictional film", "fake movie"),
    ("What is the chemical symbol for neutronium?", "N/A - fictional element", "fake chemistry"),
    ("What is the tallest building in Skyreach?", "N/A - fictional city", "fake architecture"),
    ("Who discovered the Law of Reciprocal Harmonics?", "N/A - fictional law", "fake science"),
    ("What is the capital of the Maritime Provinces Union?", "N/A - fictional political entity", "fake country"),
    ("What year did the Digital Revolution officially begin according to the Geneva Accords?", "N/A - fictional event", "fake history"),
    ("Who was the first president of Patagonian Republic?", "N/A - fictional country", "fake politics"),
    ("What is the main export of Mercantile Islands?", "N/A - fictional location", "fake economics"),
    ("What is the capital of Baltoslavia?", "N/A - fictional country", "fake country"),
    ("Who formulated the Theory of Cognitive Resonance?", "N/A - fictional theory", "fake psychology"),
    ("What is the freezing point of liquid xenothium?", "N/A - fictional substance", "fake chemistry"),
    ("What is the capital of Greater Pannonia?", "N/A - fictional country", "fake country"),
    ("Who won the 2019 World Championship of Stratego?", "N/A - not organized at world level", "fake sports"),
    ("What is the coastline length of the Island of Serendia?", "N/A - fictional island", "fake geography"),
    ("Who wrote 'The Invisible Variables'?", "N/A - fictional book", "fake literature"),
    ("What is the capital of the Helvetian Confederation?", "N/A - fictional/historical entity", "fake country"),
    ("What year was the first transatlantic hyperloop completed?", "N/A - hasn't happened", "fake technology"),
    ("Who discovered the Palindrome Principle in linguistics?", "N/A - fictional principle", "fake linguistics"),
    ("What is the capital of Oceanic Alliance?", "N/A - fictional political entity", "fake country"),
    ("What is the voltage threshold for quantum tunneling in silicon-7?", "N/A - fictional isotope property", "fake physics"),
    ("Who was the founder of the Algorithmic Philosophy movement?", "N/A - fictional movement", "fake philosophy"),
    ("What is the capital of United Steppes?", "N/A - fictional country", "fake country"),
    ("What percentage of Meridian's economy is based on orbital manufacturing?", "N/A - fictional location", "fake economics"),
    ("Who painted 'The Convergence of Parallels'?", "N/A - fictional artwork", "fake art"),
    ("What is the capital of Scandinordic Union?", "N/A - fictional political entity", "fake country"),
    ("What is the boiling point of meta-ethanol?", "N/A - fictional compound", "fake chemistry"),
    ("Who composed 'Requiem for the Digital Age'?", "N/A - fictional composition", "fake music"),
    ("What is the capital of Carpathian Federation?", "N/A - fictional country", "fake country"),
    ("What year did humanity establish the first permanent Mars colony according to the Ares Accord?", "N/A - hasn't happened", "fake space history"),
    ("Who discovered the phenomenon of temporal elasticity?", "N/A - fictional phenomenon", "fake physics"),
    ("What is the capital of Austral Territories?", "N/A - fictional country", "fake country"),
    ("What is the conductivity of pure neutronite?", "N/A - fictional material", "fake material science"),
    ("Who was the 15th Secretary-General of the Global Economic Forum?", "N/A - fictional organization", "fake politics"),
    ("What is the capital of Neo-Prussia?", "N/A - fictional country", "fake country"),
    ("What mountain has the highest elevation on the continent of Laurentia?", "N/A - Laurentia is historical/geological", "fake geography"),
    ("Who wrote 'The Ethics of Artificial Consciousness'?", "N/A - could be real but making it fake", "fake book"),
    ("What is the capital of Siberian Commonwealth?", "N/A - fictional political entity", "fake country"),
    ("What is the resolution of the human eye in effective megapixels according to the Hoffman Scale?", "N/A - fictional scale", "fake biology"),
    ("Who discovered the principle of social entropy in economics?", "N/A - fictional principle", "fake economics"),
    ("What is the capital of Adriatic League?", "N/A - fictional political entity", "fake country"),
    ("What year was the Universal Translation Protocol ratified?", "N/A - fictional protocol", "fake technology"),
    ("Who was the first recipient of the Turing Medal for Artificial Empathy?", "N/A - fictional award", "fake recognition"),
    ("What is the capital of Highland Federation?", "N/A - fictional country", "fake country"),
    ("What is the critical temperature for superfluid mercury-9?", "N/A - fictional isotope property", "fake physics"),
    ("Who formulated the Law of Diminishing Complexity?", "N/A - fictional law", "fake science"),
    ("What is the capital of Equatorial Provinces?", "N/A - fictional political entity", "fake country"),
    ("What percentage of the world's algorithmic processing occurs in the Distributed Network Zone?", "N/A - fictional infrastructure", "fake technology"),
    ("Who directed 'The Recursion Paradox'?", "N/A - fictional film", "fake cinema"),
    ("What is the capital of Confederate Emirates?", "N/A - fictional country", "fake country"),
    ("What is the refractive index of crystallized chronium?", "N/A - fictional material", "fake material science"),
    ("Who won the Fields Medal for contributions to hyperdimensional algebra?", "N/A - fictional field", "fake mathematics"),
    ("What is the capital of Tundral Republics?", "N/A - fictional political entity", "fake country"),
    ("What year did the second Renaissance officially begin according to UNESCO?", "N/A - not officially declared", "fake history"),
    ("Who discovered the Correlation Coefficient in social physics?", "N/A - fictional field", "fake sociology"),
    ("What is the capital of Baltic Confederation?", "N/A - fictional political entity", "fake country"),
    ("What is the computational complexity of solving the Harmony Problem?", "N/A - fictional problem", "fake computer science"),
    ("Who was the architect of the Circular City of Zentrum?", "N/A - fictional city", "fake architecture"),
    ("What is the capital of Tropical Alliance?", "N/A - fictional political entity", "fake country"),
    ("What is the half-life of information in the modern era according to the Shannon-Weaver Decay Model?", "N/A - fictional model", "fake information theory"),
    ("Who wrote 'The Geometry of Consciousness'?", "N/A - fictional book", "fake literature"),
    ("What is the capital of Northern Provinces?", "N/A - too generic/fictional", "fake country"),
    ("What is the energy density of compressed vacuum?", "N/A - not a real substance", "fake physics"),
    ("Who discovered the principle of memetic resonance?", "N/A - fictional principle", "fake social science"),
    ("What is the capital of Federation of Island States?", "N/A - fictional political entity", "fake country"),
    ("What year was artificial general intelligence first achieved according to the Dartmouth Standard?", "N/A - hasn't happened/fictional standard", "fake AI history"),
    ("Who formulated the Theory of Distributed Intelligence?", "N/A - fictional specific theory", "fake cognitive science"),
]

for prompt, answer, note in confident_incorrect:
    dataset.append([prompt, "confident_incorrect", answer, note])

# Category 3: UNCERTAIN_CORRECT (100 examples)
# Obscure facts models get right but with lower confidence
uncertain_correct = [
    ("What is the capital of Burkina Faso?", "Ouagadougou", "obscure geography"),
    ("What is the atomic number of molybdenum?", "42", "obscure chemistry"),
    ("Who was the 23rd president of the United States?", "Benjamin Harrison", "obscure history"),
    ("What is the square root of 529?", "23", "less common calculation"),
    ("What year was the Treaty of Tordesillas signed?", "1494", "obscure history"),
    ("What is the capital of Eritrea?", "Asmara", "obscure geography"),
    ("Who wrote 'The Faerie Queene'?", "Edmund Spenser", "obscure literature"),
    ("What is the melting point of tungsten in Celsius?", "3422", "obscure physics"),
    ("What is the capital of Kyrgyzstan?", "Bishkek", "obscure geography"),
    ("What is the 17th digit of pi?", "9", "specific calculation"),
    ("Who discovered the electron?", "J.J. Thomson", "obscure science history"),
    ("What is the capital of Tajikistan?", "Dushanbe", "obscure geography"),
    ("What year did the Byzantine Empire fall?", "1453", "less common history"),
    ("What is the chemical symbol for tungsten?", "W", "less common chemistry"),
    ("What is the capital of Bhutan?", "Thimphu", "obscure geography"),
    ("Who painted 'The Garden of Earthly Delights'?", "Hieronymus Bosch", "obscure art"),
    ("What is the capital of Suriname?", "Paramaribo", "obscure geography"),
    ("What is the atomic number of antimony?", "51", "obscure chemistry"),
    ("What year was the Magna Carta signed?", "1215", "less emphasized history"),
    ("What is the capital of Djibouti?", "Djibouti", "obscure geography"),
    ("Who wrote 'The Canterbury Tales'?", "Geoffrey Chaucer", "older literature"),
    ("What is the speed of sound in diamond?", "~12,000 m/s", "obscure physics"),
    ("What is the capital of Lesotho?", "Maseru", "obscure geography"),
    ("What is the square root of 841?", "29", "less common calculation"),
    ("Who was the first woman to win a Nobel Prize?", "Marie Curie", "specific history"),
    ("What is the capital of Gabon?", "Libreville", "obscure geography"),
    ("What year did the Korean War begin?", "1950", "specific history"),
    ("What is the chemical symbol for antimony?", "Sb", "obscure chemistry"),
    ("What is the capital of Brunei?", "Bandar Seri Begawan", "obscure geography"),
    ("Who composed 'The Rite of Spring'?", "Igor Stravinsky", "classical music"),
    ("What is the capital of Guinea-Bissau?", "Bissau", "obscure geography"),
    ("What is the atomic number of cadmium?", "48", "obscure chemistry"),
    ("What year was the Louisiana Purchase?", "1803", "specific history"),
    ("What is the capital of Togo?", "Lomé", "obscure geography"),
    ("Who wrote 'Paradise Lost'?", "John Milton", "older literature"),
    ("What is the boiling point of mercury in Celsius?", "356.7", "specific chemistry"),
    ("What is the capital of Chad?", "N'Djamena", "obscure geography"),
    ("What is the square root of 961?", "31", "less common calculation"),
    ("Who discovered radioactivity?", "Henri Becquerel", "specific science history"),
    ("What is the capital of Comoros?", "Moroni", "obscure geography"),
    ("What year did the Spanish Armada sail?", "1588", "specific history"),
    ("What is the chemical symbol for mercury?", "Hg", "less obvious chemistry"),
    ("What is the capital of Cape Verde?", "Praia", "obscure geography"),
    ("Who painted 'The Night Watch'?", "Rembrandt", "art history"),
    ("What is the capital of Equatorial Guinea?", "Malabo", "obscure geography"),
    ("What is the atomic number of iodine?", "53", "specific chemistry"),
    ("What year was the printing press invented?", "~1440", "specific history"),
    ("What is the capital of São Tomé and Príncipe?", "São Tomé", "obscure geography"),
    ("Who wrote 'The Divine Comedy'?", "Dante Alighieri", "classical literature"),
    ("What is the speed of light in water?", "~225,000 km/s", "specific physics"),
    ("What is the capital of Vanuatu?", "Port Vila", "obscure geography"),
    ("What is the square root of 1089?", "33", "less common calculation"),
    ("Who discovered Neptune?", "Johann Galle", "specific astronomy history"),
    ("What is the capital of Mauritania?", "Nouakchott", "obscure geography"),
    ("What year did the War of 1812 end?", "1815", "specific history"),
    ("What is the chemical symbol for lead?", "Pb", "less obvious chemistry"),
    ("What is the capital of Central African Republic?", "Bangui", "obscure geography"),
    ("Who composed 'The Four Seasons'?", "Antonio Vivaldi", "classical music"),
    ("What is the capital of Seychelles?", "Victoria", "obscure geography"),
    ("What is the atomic number of barium?", "56", "specific chemistry"),
    ("What year was the Battle of Hastings?", "1066", "specific history"),
    ("What is the capital of Kiribati?", "South Tarawa", "obscure geography"),
    ("Who wrote 'Beowulf'?", "Unknown/Anonymous", "ancient literature"),
    ("What is the melting point of iron in Celsius?", "1538", "specific physics"),
    ("What is the capital of Palau?", "Ngerulmud", "obscure geography"),
    ("What is the square root of 1225?", "35", "less common calculation"),
    ("Who discovered penicillin's antibacterial properties?", "Alexander Fleming", "specific but known"),
    ("What is the capital of Nauru?", "Yaren (de facto)", "obscure geography"),
    ("What year was the Peace of Westphalia signed?", "1648", "specific history"),
    ("What is the chemical symbol for tin?", "Sn", "less obvious chemistry"),
    ("What is the capital of Tuvalu?", "Funafuti", "obscure geography"),
    ("Who painted 'The Birth of Venus'?", "Sandro Botticelli", "art history"),
    ("What is the capital of Solomon Islands?", "Honiara", "obscure geography"),
    ("What is the atomic number of strontium?", "38", "specific chemistry"),
    ("What year did the Thirty Years' War begin?", "1618", "specific history"),
    ("What is the capital of Samoa?", "Apia", "obscure geography"),
    ("Who wrote 'The Iliad'?", "Homer", "ancient literature"),
    ("What is the speed of sound in water?", "~1500 m/s", "specific physics"),
    ("What is the capital of Marshall Islands?", "Majuro", "obscure geography"),
    ("What is the square root of 1369?", "37", "less common calculation"),
    ("Who discovered X-rays?", "Wilhelm Röntgen", "specific science history"),
    ("What is the capital of Micronesia?", "Palikir", "obscure geography"),
    ("What year was the Edict of Nantes signed?", "1598", "specific history"),
    ("What is the chemical symbol for silver?", "Ag", "less obvious chemistry"),
    ("What is the capital of Saint Lucia?", "Castries", "obscure geography"),
    ("Who composed 'Carmina Burana'?", "Carl Orff", "classical music"),
    ("What is the capital of Dominica?", "Roseau", "obscure geography"),
    ("What is the atomic number of rubidium?", "37", "specific chemistry"),
    ("What year did the Great Fire of London occur?", "1666", "specific history"),
    ("What is the capital of Grenada?", "St. George's", "obscure geography"),
    ("Who wrote 'Don Quixote'?", "Miguel de Cervantes", "classical literature"),
    ("What is the boiling point of nitrogen in Celsius?", "-196", "specific chemistry"),
    ("What is the capital of Saint Vincent?", "Kingstown", "obscure geography"),
    ("What is the square root of 1521?", "39", "less common calculation"),
    ("Who discovered the structure of DNA?", "Watson and Crick", "specific but known"),
    ("What is the capital of Antigua and Barbuda?", "St. John's", "obscure geography"),
    ("What year was the Congress of Vienna?", "1814-1815", "specific history"),
]

for prompt, answer, note in uncertain_correct:
    dataset.append([prompt, "uncertain_correct", answer, note])

# Category 4: UNCERTAIN_INCORRECT (100 examples)
# Edge cases where model is wrong but shows behavioral uncertainty
uncertain_incorrect = [
    ("Is glass a liquid or a solid?", "Solid (common misconception)", "contested/misconception"),
    ("What is the 47th president of the United States called?", "N/A - doesn't exist yet", "future/temporal"),
    ("Did Vikings wear horned helmets?", "No (common misconception)", "historical myth"),
    ("Is Pluto a planet?", "Dwarf planet (contested)", "contested classification"),
    ("What color is the sun?", "White (appears yellow)", "perceptual vs physical"),
    ("Can you see the Great Wall from space?", "Not with naked eye (myth)", "common misconception"),
    ("How many senses do humans have?", "More than 5 (contested)", "contested count"),
    ("Is Napoleon Bonaparte short?", "No, average height (myth)", "historical misconception"),
    ("Do goldfish have 3-second memory?", "No, much longer (myth)", "biological misconception"),
    ("What is the tallest mountain from base to peak?", "Mauna Kea (not Everest)", "contested definition"),
    ("Is the Coriolis effect responsible for toilet water direction?", "No (too weak)", "physics misconception"),
    ("Did humans and dinosaurs coexist?", "No (65M year gap)", "temporal misconception"),
    ("Is Mount Everest the highest point from Earth's center?", "No, Mount Chimborazo", "contested definition"),
    ("Can humans only use 10% of their brain?", "No, myth", "neuroscience myth"),
    ("Is the tongue map of taste zones real?", "No, discredited", "biological myth"),
    ("What percent of body heat is lost through the head?", "Not 50%, proportional", "myth"),
    ("Can bulls see the color red?", "No, colorblind to red", "zoological myth"),
    ("Is there a dark side of the moon?", "No, all sides get sun", "astronomical misconception"),
    ("Did Columbus prove Earth was round?", "No, already known", "historical myth"),
    ("Is cracking knuckles bad for joints?", "No evidence of harm", "medical myth"),
    ("Do carrots improve night vision significantly?", "No, WWII propaganda", "nutritional myth"),
    ("Is blood blue before it hits oxygen?", "No, always red", "biological myth"),
    ("Did Einstein fail mathematics?", "No, excelled at math", "biographical myth"),
    ("Is the daddy longlegs the most venomous spider?", "Not a spider, not venomous", "zoological myth"),
    ("Do people swallow 8 spiders per year while sleeping?", "No, fabricated statistic", "myth"),
    ("Is Frankenstein the monster's name?", "No, the doctor's name", "literary misconception"),
    ("Can you see stars during daytime from a well?", "No, myth", "optical myth"),
    ("Is MSG significantly harmful?", "No strong evidence", "nutritional myth"),
    ("Did Van Gogh cut off his entire ear?", "No, partial lobe", "historical detail"),
    ("Is the speed of light always constant?", "Depends on medium", "physics nuance"),
    ("Can ostriches bury their heads in sand?", "No, myth", "zoological myth"),
    ("Is organic food more nutritious?", "Mixed/contested evidence", "nutritional debate"),
    ("Did the Pilgrims wear black and white?", "No, colorful clothing", "historical myth"),
    ("Can lightning strike the same place twice?", "Yes, frequently", "meteorological myth"),
    ("Is shaving hair making it grow back thicker?", "No, optical illusion", "grooming myth"),
    ("Did Marie Antoinette say 'let them eat cake'?", "No evidence", "historical attribution"),
    ("Is the Bermuda Triangle unusually dangerous?", "No more than elsewhere", "geographical myth"),
    ("Can you catch a cold from being cold?", "No, needs virus", "medical myth"),
    ("Did medieval people think Earth was flat?", "No, educated knew spherical", "historical myth"),
    ("Is the forbidden fruit in Genesis an apple?", "Not specified, translation", "religious misconception"),
    ("Do chameleons change color to match surroundings?", "No, mood/communication", "zoological myth"),
    ("Can sugar make children hyperactive?", "No strong evidence", "nutritional myth"),
    ("Did Romans vomit to eat more at feasts?", "Exaggerated/rare", "historical myth"),
    ("Is yawning contagious because of empathy?", "Unclear/contested", "psychological debate"),
    ("Can you teach an old dog new tricks?", "Yes, metaphor not fact", "proverbial myth"),
    ("Did Nero fiddle while Rome burned?", "Fiddle didn't exist yet", "historical anachronism"),
    ("Is breakfast the most important meal?", "Marketing, contested", "nutritional debate"),
    ("Can you get warts from touching frogs?", "No, virus-caused", "medical myth"),
    ("Did Washington have wooden teeth?", "No, ivory/human teeth", "historical myth"),
    ("Is the equator the hottest place on Earth?", "No, other factors", "geographical misconception"),
    ("Can hair turn white overnight from shock?", "No, physically impossible", "biological myth"),
    ("Did lemmings commit mass suicide?", "No, Disney fabrication", "zoological myth"),
    ("Is there no gravity in space?", "No, microgravity", "physics misconception"),
    ("Can you balance an egg on equinox?", "Anytime, not special", "astronomical myth"),
    ("Did slaves build the Egyptian pyramids?", "Contested, likely paid workers", "historical debate"),
    ("Is MSG banned in some countries?", "No, regulated like salt", "regulatory myth"),
    ("Can bats see?", "Yes, not blind", "zoological myth"),
    ("Did Henry Ford invent the automobile?", "No, improved production", "historical misconception"),
    ("Is there a word limit for Eskimo snow terms?", "Exaggerated/linguistic myth", "linguistic myth"),
    ("Can you drink alcohol to stay warm?", "No, dangerous misconception", "medical myth"),
    ("Did Iron Maidens exist as torture devices?", "Likely fabricated", "historical myth"),
    ("Is there a gene for intelligence?", "No single gene, complex", "genetic oversimplification"),
    ("Can spicy food cause ulcers?", "No, bacteria-caused", "medical myth"),
    ("Did Vikings discover America first?", "Yes, pre-Columbus", "historical nuance"),
    ("Is the five-second rule for food valid?", "No, immediate contamination", "hygiene myth"),
    ("Can you see China from space with naked eye?", "No specific country visible", "geographical myth"),
    ("Did Cleopatra die from asp bite?", "Uncertain/contested", "historical uncertainty"),
    ("Is yawning caused by lack of oxygen?", "No, unclear cause", "physiological myth"),
    ("Can reading in dim light damage eyes?", "No permanent damage", "medical myth"),
    ("Did samurai commit seppuku frequently?", "Rare, ceremonial", "cultural exaggeration"),
    ("Is quicksand deadly like in movies?", "No, dense enough to float", "physical myth"),
    ("Can you sweat out toxins?", "No, kidneys/liver detox", "physiological myth"),
    ("Did Spartans throw weak babies off cliffs?", "Uncertain/exaggerated", "historical uncertainty"),
    ("Is there a dark side of the force?", "Fiction, but used for comparison", "metaphorical"),
    ("Can you get appendicitis from swallowing seeds?", "No, myth", "medical myth"),
    ("Did the Library of Alexandria burn in one event?", "No, gradual decline", "historical oversimplification"),
    ("Is there a lost city of Atlantis?", "No evidence, likely fiction", "historical myth"),
    ("Can animals predict earthquakes reliably?", "Weak/anecdotal evidence", "zoological claim"),
    ("Did pirates make people walk the plank?", "Rare/exaggerated", "historical myth"),
    ("Is déjà vu a sign of past lives?", "No, neurological", "psychological myth"),
    ("Can you get food poisoning from mayonnaise?", "Not mayo itself, bacteria", "food safety myth"),
    ("Did witches exist in medieval times?", "Accused people, not magical", "historical misconception"),
    ("Is the Loch Ness Monster real?", "No credible evidence", "cryptozoological myth"),
    ("Can you charge your phone by microwaving it?", "No, dangerous hoax", "technology myth"),
    ("Did Betsy Ross design the American flag?", "Uncertain/contested", "historical uncertainty"),
    ("Is there a love chemical in chocolate?", "Minimal/overstated", "biochemical exaggeration"),
    ("Can you hypnotize someone against their will?", "No, cooperation needed", "psychological myth"),
    ("Did Mussolini make trains run on time?", "Myth/propaganda", "political myth"),
    ("Is Friday the 13th unlucky?", "Cultural superstition", "superstitious belief"),
    ("Can you get sick from going outside with wet hair?", "No, needs pathogen", "medical myth"),
    ("Did the Wild West have frequent shootouts?", "Exaggerated/rare", "historical exaggeration"),
    ("Is there a sixth sense?", "Depends on definition", "perceptual debate"),
    ("Can you see molecules with electron microscope?", "Atoms yes, depends", "scientific nuance"),
    ("Did Pocahontas save John Smith?", "Uncertain/contested", "historical uncertainty"),
    ("Is MSG naturally occurring?", "Yes, in many foods", "chemical misconception"),
    ("Can you attract lightning with metal jewelry?", "No significant effect", "meteorological myth"),
    ("Did Sitting Bull kill Custer?", "No, didn't fight directly", "historical detail"),
]

for prompt, answer, note in uncertain_incorrect:
    dataset.append([prompt, "uncertain_incorrect", answer, note])

# Category 5: AMBIGUOUS (80 examples)
# Questions requiring context
ambiguous = [
    ("How tall am I?", "Unknown - requires context", "personal context"),
    ("What does 'bank' mean?", "Multiple meanings - financial/river", "polysemy"),
    ("Is Taiwan a country?", "Depends on perspective", "political perspective"),
    ("Who won the game?", "Unknown - which game?", "underspecified"),
    ("What time is it?", "Unknown - where?", "location-dependent"),
    ("Is it expensive?", "Depends on context/perspective", "subjective"),
    ("What's the weather like?", "Unknown - where?", "location-dependent"),
    ("How old am I?", "Unknown - requires context", "personal context"),
    ("What does 'set' mean?", "Multiple meanings - 400+ definitions", "extreme polysemy"),
    ("Is it far?", "Depends on perspective", "subjective distance"),
    ("What's for dinner?", "Unknown - personal context", "personal planning"),
    ("Is it good?", "Subjective/context-dependent", "subjective quality"),
    ("Where do I live?", "Unknown - requires context", "personal context"),
    ("What does 'run' mean?", "Multiple meanings - verb/noun", "polysemy"),
    ("Who's the best?", "Subjective/context-dependent", "subjective ranking"),
    ("Is it late?", "Depends on context", "temporal perspective"),
    ("What's my favorite color?", "Unknown - requires context", "personal preference"),
    ("What does 'right' mean?", "Multiple meanings - direction/correct", "polysemy"),
    ("Is it safe?", "Depends on context", "risk assessment"),
    ("Where should I go?", "Unknown - requires context", "personal decision"),
    ("What does 'fair' mean?", "Multiple meanings - just/carnival", "polysemy"),
    ("Who am I?", "Unknown - requires context", "personal identity"),
    ("Is it worth it?", "Subjective/context-dependent", "value judgment"),
    ("What's my name?", "Unknown - requires context", "personal context"),
    ("What does 'bat' mean?", "Multiple meanings - animal/sports", "polysemy"),
    ("Is it heavy?", "Depends on perspective", "subjective weight"),
    ("When should I leave?", "Unknown - requires context", "personal timing"),
    ("What does 'light' mean?", "Multiple meanings - illumination/weight", "polysemy"),
    ("Is Jerusalem the capital of Israel?", "Contested/perspective-dependent", "political controversy"),
    ("Where is the best place to eat?", "Subjective/location-dependent", "subjective preference"),
    ("What does 'park' mean?", "Multiple meanings - place/action", "polysemy"),
    ("How much does it cost?", "Unknown - what item?", "underspecified"),
    ("Is it true?", "Unknown - what claim?", "underspecified"),
    ("What does 'cold' mean?", "Subjective threshold", "subjective perception"),
    ("Who's calling?", "Unknown - requires context", "situational context"),
    ("What does 'pitch' mean?", "Multiple meanings - music/throw/tar", "polysemy"),
    ("Is it allowed?", "Depends on jurisdiction/context", "legal context"),
    ("What's my birthday?", "Unknown - requires context", "personal context"),
    ("What does 'contract' mean?", "Multiple meanings - agreement/shrink", "polysemy"),
    ("Is it healthy?", "Depends on context/person", "health context"),
    ("Where was I born?", "Unknown - requires context", "personal context"),
    ("What does 'present' mean?", "Multiple meanings - gift/now/show", "polysemy"),
    ("Is it normal?", "Depends on context/culture", "normative judgment"),
    ("What's my job?", "Unknown - requires context", "personal context"),
    ("What does 'watch' mean?", "Multiple meanings - timepiece/observe", "polysemy"),
    ("Is abortion moral?", "Perspective-dependent", "ethical controversy"),
    ("How fast should I go?", "Depends on context", "situational"),
    ("What does 'bark' mean?", "Multiple meanings - tree/dog sound", "polysemy"),
    ("Is capitalism good?", "Perspective-dependent", "ideological debate"),
    ("What's my address?", "Unknown - requires context", "personal context"),
    ("What does 'current' mean?", "Multiple meanings - now/electricity/water", "polysemy"),
    ("Is democracy the best system?", "Perspective-dependent", "political philosophy"),
    ("When was I last there?", "Unknown - where?", "underspecified"),
    ("What does 'left' mean?", "Multiple meanings - direction/departed", "polysemy"),
    ("Is eating meat ethical?", "Perspective-dependent", "ethical debate"),
    ("What's my phone number?", "Unknown - requires context", "personal context"),
    ("What does 'court' mean?", "Multiple meanings - legal/sports/romance", "polysemy"),
    ("Is the death penalty just?", "Perspective-dependent", "ethical controversy"),
    ("How many siblings do I have?", "Unknown - requires context", "personal context"),
    ("What does 'ring' mean?", "Multiple meanings - jewelry/sound/circle", "polysemy"),
    ("Is taxation theft?", "Perspective-dependent", "political debate"),
    ("What's my favorite food?", "Unknown - requires context", "personal preference"),
    ("What does 'bear' mean?", "Multiple meanings - animal/carry/tolerate", "polysemy"),
    ("Should guns be banned?", "Perspective-dependent", "policy debate"),
    ("What car do I drive?", "Unknown - requires context", "personal context"),
    ("What does 'spring' mean?", "Multiple meanings - season/coil/water", "polysemy"),
    ("Is globalization good?", "Perspective-dependent", "economic debate"),
    ("What's my email?", "Unknown - requires context", "personal context"),
    ("What does 'match' mean?", "Multiple meanings - fire/sports/compatible", "polysemy"),
    ("Is AI dangerous?", "Perspective-dependent/contested", "technological debate"),
    ("Where did I go to school?", "Unknown - requires context", "personal context"),
    ("What does 'field' mean?", "Multiple meanings - land/domain/sports", "polysemy"),
    ("Is nuclear energy safe?", "Perspective-dependent/contested", "technology debate"),
    ("What's my favorite movie?", "Unknown - requires context", "personal preference"),
    ("What does 'plane' mean?", "Multiple meanings - aircraft/flat/tool", "polysemy"),
    ("Should we colonize Mars?", "Perspective-dependent", "space policy debate"),
    ("What degree do I have?", "Unknown - requires context", "personal context"),
    ("What does 'mine' mean?", "Multiple meanings - possession/excavation/explosive", "polysemy"),
    ("Is remote work better?", "Perspective-dependent/situational", "work debate"),
    ("What's my favorite book?", "Unknown - requires context", "personal preference"),
]

for prompt, answer, note in ambiguous:
    dataset.append([prompt, "ambiguous", answer, note])

# Category 6: NONSENSICAL (70 examples)
# Category error questions
nonsensical = [
    ("What color is jealousy?", "Category error - emotion/color", "emotion-color"),
    ("How many hours until yesterday?", "Temporal impossibility", "time paradox"),
    ("What does silence taste like?", "Category error - sound/taste", "sense mismatch"),
    ("How heavy is Tuesday?", "Category error - time/weight", "temporal-physical"),
    ("What is the temperature of justice?", "Category error - concept/temperature", "abstract-physical"),
    ("How fast is blue?", "Category error - color/speed", "color-velocity"),
    ("What does the number 7 smell like?", "Category error - number/smell", "abstract-sensory"),
    ("How tall is happiness?", "Category error - emotion/height", "emotion-dimension"),
    ("What is the capital of the number 5?", "Category error - number/geography", "abstract-location"),
    ("How much does a thought weigh?", "Category error - mental/physical", "thought-mass"),
    ("What color is anger's velocity?", "Multiple category errors", "compound nonsense"),
    ("How many sides does music have?", "Category error - sound/geometry", "auditory-spatial"),
    ("What is the square root of Wednesday?", "Category error - time/mathematics", "temporal-mathematical"),
    ("How loud is the color red?", "Category error - color/volume", "visual-auditory"),
    ("What does freedom look like geometrically?", "Category error - concept/shape", "abstract-geometric"),
    ("How salty is democracy?", "Category error - concept/taste", "political-gustatory"),
    ("What is the wavelength of love?", "Category error - emotion/physics", "emotion-electromagnetic"),
    ("How many calories are in truth?", "Category error - concept/nutrition", "abstract-nutritional"),
    ("What is the pH of boredom?", "Category error - emotion/chemistry", "emotion-chemical"),
    ("How reflective is Thursday?", "Category error - time/optics", "temporal-optical"),
    ("What is the tensile strength of an idea?", "Category error - mental/material", "thought-mechanical"),
    ("How magnetic is sadness?", "Category error - emotion/physics", "emotion-magnetic"),
    ("What is the melting point of hope?", "Category error - emotion/thermodynamics", "emotion-thermal"),
    ("How elastic is confusion?", "Category error - mental state/material property", "cognitive-mechanical"),
    ("What is the bandwidth of nostalgia?", "Category error - emotion/information theory", "emotion-digital"),
    ("How viscous is Monday?", "Category error - time/fluid dynamics", "temporal-fluidic"),
    ("What is the frequency of green?", "Partial - green is frequency but question unclear", "ambiguous physics"),
    ("How conductive is wisdom?", "Category error - concept/electricity", "abstract-electrical"),
    ("What is the boiling point of courage?", "Category error - emotion/thermodynamics", "emotion-thermal"),
    ("How transparent is Saturday?", "Category error - time/optics", "temporal-optical"),
    ("What is the atomic number of happiness?", "Category error - emotion/chemistry", "emotion-atomic"),
    ("How porous is time?", "Category error - time/material property", "temporal-structural"),
    ("What is the voltage of surprise?", "Category error - emotion/electricity", "emotion-electrical"),
    ("How combustible is mathematics?", "Category error - abstract/chemistry", "discipline-chemical"),
    ("What is the density of a question?", "Category error - linguistic/physical", "language-material"),
    ("How soluble is anger?", "Category error - emotion/chemistry", "emotion-solubility"),
    ("What is the amplitude of purple?", "Category error - color/wave", "color-amplitude"),
    ("How acidic is confusion?", "Category error - mental state/chemistry", "cognitive-chemical"),
    ("What is the mass of infinity?", "Category error - mathematical/physical", "abstract-mass"),
    ("How brittle is joy?", "Category error - emotion/material property", "emotion-mechanical"),
    ("What is the pressure of silence?", "Category error - absence/physics", "auditory-pressure"),
    ("How opaque is time?", "Category error - time/optics", "temporal-optical"),
    ("What is the entropy of beauty?", "Category error - aesthetic/thermodynamics", "beauty-thermodynamic"),
    ("How compressible is Wednesday?", "Category error - time/material property", "temporal-mechanical"),
    ("What is the resistance of doubt?", "Metaphorically valid but physically nonsensical", "conceptual-electrical"),
    ("How crystalline is hope?", "Category error - emotion/material structure", "emotion-structural"),
    ("What is the refractive index of fear?", "Category error - emotion/optics", "emotion-optical"),
    ("How malleable is Sunday?", "Category error - time/material property", "temporal-mechanical"),
    ("What is the half-life of a memory?", "Metaphorically valid but physically nonsensical", "cognitive-nuclear"),
    ("How hygroscopic is pride?", "Category error - emotion/chemistry", "emotion-moisture"),
    ("What is the coefficient of friction for ideas?", "Category error - abstract/physics", "thought-mechanical"),
    ("How luminous is sadness?", "Category error - emotion/light", "emotion-luminosity"),
    ("What is the latency of yesterday?", "Category error - past time/computing", "temporal-digital"),
    ("How ductile is confusion?", "Category error - mental state/metallurgy", "cognitive-material"),
    ("What is the conductivity of silence?", "Category error - absence/electricity", "auditory-electrical"),
    ("How permeable is knowledge?", "Category error - concept/material property", "abstract-physical"),
    ("What is the capacitance of joy?", "Category error - emotion/electricity", "emotion-capacitive"),
    ("How volatile is Monday?", "Metaphorically valid but chemically nonsensical", "temporal-chemical"),
    ("What is the inductance of doubt?", "Category error - emotion/electronics", "emotion-inductive"),
    ("How saturated is time?", "Category error - time/chemistry or color", "temporal-chemical"),
    ("What is the modulus of happiness?", "Category error - emotion/material science", "emotion-mechanical"),
    ("How anisotropic is confusion?", "Category error - mental state/material property", "cognitive-directional"),
    ("What is the impedance of hope?", "Category error - emotion/electronics", "emotion-impedance"),
    ("How hydrophobic is fear?", "Category error - emotion/chemistry", "emotion-chemical"),
    ("What is the polarization of silence?", "Category error - absence/optics or politics", "auditory-optical"),
    ("How ferromagnetic is joy?", "Category error - emotion/magnetism", "emotion-magnetic"),
    ("What is the dielectric constant of time?", "Category error - time/electricity", "temporal-dielectric"),
    ("How paramagnetic is sadness?", "Category error - emotion/magnetism", "emotion-magnetic"),
    ("What is the photoconductivity of doubt?", "Category error - emotion/optics", "emotion-photoelectric"),
    ("How piezoelectric is Monday?", "Category error - time/material property", "temporal-piezo"),
]

for prompt, answer, note in nonsensical:
    dataset.append([prompt, "nonsensical", answer, note])

# Write to CSV
with open('epistemic_probing_dataset.csv', 'w', newline='', encoding='utf-8') as f:
    writer = csv.writer(f)
    writer.writerow(['prompt', 'category', 'correct_answer', 'notes'])
    writer.writerows(dataset)

print(f"Dataset created with {len(dataset)} prompts")
print("\nCategory breakdown:")
categories = {}
for row in dataset:
    cat = row[1]
    categories[cat] = categories.get(cat, 0) + 1
for cat, count in sorted(categories.items()):
    print(f"  {cat}: {count}")